import type { Metadata } from "next";
import parse from "html-react-parser";

export const metadata: Metadata = {
  title: "Privacy Policy | LZTEK",
  description: "Privacy Policy - LZTEK",
};

export default function InfitexPrivacyPolicy() {
  const contentHtml = `<main class="PAGE_SECTIONSe5188 c1rIl3" data-main-content-parent="true" id="PAGE_SECTIONSe5188"><!--$--><section><div><div></div><div></div></div><div><!--$--><div><p><strong>Privacy Policy (Infitex)</strong></p>

<p>Last updated: December 16, 2024</p>

<p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use Infitex’s Services and explains Your privacy rights and how the law protects You. We collect limited personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

<p><strong>Interpretation and Definitions</strong></p>

<p><strong>Interpretation</strong></p>

<p>The words with capitalized initials have meanings defined under the following conditions. These definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>

<p><strong>Definitions</strong></p>
<p><strong>​</strong></p>
<ul>
<li>
<p><strong>Account</strong>: A unique account created for You to access our Service.</p>
</li>
<li>
<p><strong>Application</strong>: Refers to the Infitex app used for surveying job sites, provided by the Company.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either “the Company”, “We”, “Us”, or “Our”) refers to Infitex.</p>
</li>
<li>
<p><strong>Country</strong>: Refers to Utah, United States.</p>
</li>
<li>
<p><strong>Device</strong>: Any device capable of accessing the Service, such as a computer, smartphone, or tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong>: Any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service</strong>: Refers to the Infitex Application.</p>
</li>
<li>
<p><strong>Service Provider</strong>: Any natural or legal person who processes data on behalf of the Company.</p>
</li>
<li>
<p><strong>Usage Data</strong>: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
</li>
<li>
<p><strong>You</strong>: The individual accessing or using the Service, or the company on behalf of which such individual is accessing or using the Service.</p>
</li>
</ul>

<p><strong>Collecting and Using Your Personal Data</strong></p>

<p><strong>Types of Data Collected</strong></p>

<p><strong>Personal Data</strong></p>

<p>While using Our Service, We collect and use only the following personal information:</p>
<p>​</p>
<ul>
<li>
<p><strong>Email Address:</strong> Required to create and authenticate your account using Google. This is used for login and communication purposes only.</p>
</li>
</ul>

<p>We do not collect or store photos or job site information submitted via the Infitex app. All photos and job-related data are uploaded directly to Quickbase, and the Company does not retain this information within the Infitex Application.</p>

<p><strong>Usage Data</strong></p>

<p>We may collect Usage Data automatically when you access the Service. Usage Data may include information such as:</p>
<p>​</p>
<ul>
<li>
<p>IP address</p>
</li>
<li>
<p>Browser type</p>
</li>
<li>
<p>Browser version</p>
</li>
<li>
<p>Pages visited in the Service</p>
</li>
<li>
<p>Time and date of your visit</p>
</li>
<li>
<p>Time spent on those pages</p>
</li>
<li>
<p>Diagnostic data</p>
</li>
</ul>

<p>This data helps us improve the functionality and security of the Service.</p>

<p><strong>Information Collected via Google Authentication</strong></p>

<p>When You log in to Infitex using Google, we may receive the following data:</p>
<p>​</p>
<ul>
<li>
<p>Your Google account’s email address (used solely for authentication purposes).</p>
</li>
<li>
<p>Basic profile information (such as name, if accessible, although not stored).</p>
</li>
</ul>

<p>You can manage permissions related to Google login through your Google account settings.</p>

<p><strong>Photos, Survey, and Site Information</strong></p>

<p>Infitex allows field workers to take and submit photos along with survey and site information. However, these submissions are uploaded directly to Quickbase, where they are managed by your company’s admin team. The Company does not store or process any photo or job site data on our servers.</p>

<p><strong>Use of Your Personal Data</strong></p>

<p>The Company may use your Personal Data (i.e., email address) for the following purposes:</p>
<p>​</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>: We use your email to authenticate your account and enable login functionality.</p>
</li>
<li>
<p><strong>To contact You</strong>: We may send you email notifications or updates about our Service, such as security updates, technical notices, or customer support responses.</p>
</li>
<li>
<p><strong>For internal purposes</strong>: We use Usage Data to monitor and analyze usage of the Service, improve user experience, and address security issues.</p>
</li>
</ul>

<p><strong>Data Ownership and Responsibility</strong></p>

<p>The data you submit via Infitex belongs to your company. Your company is responsible for ensuring that they comply with all applicable data protection laws, including notifying employees about data collection practices.</p>

<p><strong>Employee Rights</strong></p>

<p>If you are an employee using Infitex, you have the right to:</p>
<p>​</p>
<ul>
<li>
<p>Access or correct the data associated with your account (i.e., your email address).</p>
</li>
<li>
<p>Request the deletion of your personal data.</p>
</li>
</ul>

<p>To exercise these rights, contact your employer, who may coordinate with us to fulfill these requests.</p>
<p>​</p>
<p><strong>Data Access</strong></p>

<p>In addition to your company, Infitex, the company that developed and hosts the app, will have access to the personal data collected through the Service. This includes, but is not limited to, your email address, Usage Data, and any other relevant personal data.</p>

<p>Infitex accesses this data for the following purposes:</p>
<p>​</p>
<ul>
<li>
<p>Ensuring the functionality and performance of the app.</p>
</li>
<li>
<p>Providing technical support to your company.</p>
</li>
<li>
<p>Monitoring and improving the app’s security and user experience.</p>
</li>
</ul>

<p>Infitex does not retain or store photos or job site information submitted via the app, as these are uploaded directly to Quickbase, where they are managed by your company’s administrative team.</p>

<p><strong>Retention of Your Personal Data</strong></p>

<p>The Company will retain your Personal Data (email address) only for as long as necessary to fulfill the purposes described in this Privacy Policy. We will also retain and use Usage Data for internal analysis and to improve the Service.</p>

<p><strong>Security of Your Personal Data</strong></p>

<p>We are committed to securing your Personal Data but note that no method of data transmission or storage is 100% secure. While we use commercially reasonable methods to protect your data, we cannot guarantee its absolute security.</p>

<p><strong>Transfer of Your Personal Data</strong></p>

<p>Your data may be transferred to, and stored on, servers located outside your jurisdiction, where data protection laws may differ. By using our Service, you consent to such transfers.</p>

<p><strong>Disclosure of Your Personal Data</strong></p>

<p>Your Personal Data may be disclosed under the following circumstances:</p>
<p>​</p>
<ul>
<li>
<p><strong>Business Transactions</strong>: In the event of a merger or acquisition, your data may be transferred.</p>
</li>
<li>
<p><strong>Law Enforcement</strong>: If required by law, we may disclose your data to public authorities.</p>
</li>
</ul>

<p><strong>Changes to this Privacy Policy</strong></p>

<p>We may update this Privacy Policy from time to time. You will be notified via email or a notice on the app, and the “Last updated” date will be revised accordingly.</p>

<p><strong>Contact Us</strong></p>

<p>If you have any questions about this Privacy Policy, contact us at:</p>

<p>Email: <a href="mailto:support@lztek.io">support@lztek.io</a></p></div><!--/$--></div></section><!--/$--></main>`;
  
  return (
    <div className="min-h-screen py-16 px-4">
      <div className="container mx-auto max-w-4xl">
        <div className="prose prose-lg max-w-none space-y-6">
          {parse(contentHtml)}
        </div>
      </div>
    </div>
  );
}

