import type { Metadata } from "next";
import parse from "html-react-parser";

export const metadata: Metadata = {
  title: "Privacy Policy | LZTEK",
  description: "Privacy Policy - LZTEK",
};

export default function NocodeflexPrivacyPolicy() {
  const contentHtml = `<main class="PAGE_SECTIONSc5ada c1rIl3" data-main-content-parent="true" id="PAGE_SECTIONSc5ada"><!--$--><section><div><div></div><div></div></div><div><!--$--><div><p>Privacy Policy (<strong>NoCode Flex</strong>)</p>
<p>​</p>
<p>Last updated: March 10, 2025</p>

<p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use NoCode Flex’s Services and explains Your privacy rights and how the law protects You. We collect limited personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
<p>​</p>
<p>Interpretation and Definitions</p>
<p>​</p>
<p>Interpretation</p>
<p>The words with capitalized initials have meanings defined under the following conditions. These definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
<p>​</p>
<p>Definitions</p>
<p>​</p>
<ul>
<li>
<p><strong>Account:</strong> A unique account created for You to access our Service.</p>
</li>
<li>
<p><strong>Application:</strong> Refers to the NoCode Flex app used for digital workflow automation, provided by the Company.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either “the Company,” “We,” “Us,” or “Our”) refers to LZTEK, LLC.</p>
</li>
<li>
<p><strong>Country:</strong> Refers to the United States.</p>
</li>
<li>
<p><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, smartphone, or tablet.</p>
</li>
<li>
<p><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service:</strong> Refers to the NoCode Flex Application.</p>
</li>
<li>
<p><strong>Service Provider:</strong> Any natural or legal person who processes data on behalf of the Company.</p>
</li>
<li>
<p><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
</li>
<li>
<p><strong>You:</strong> The individual accessing or using the Service.</p>
</li>
</ul>

<p>Public Nature of the Service</p>
<p>​</p>
<p>NoCode Flex is a publicly available demo application designed to allow individuals to interact with and modify system contents. By using the Service, You acknowledge and agree that:</p>
<p>​</p>
<ul>
<li>
<p>Other users will have public access to the data and content you submit within the system.</p>
</li>
<li>
<p>Any modifications, updates, or contributions you make to the system will be visible to all users.</p>
</li>
<li>
<p>NoCode Flex does not guarantee the privacy or confidentiality of any non-account-related information entered into the system.</p>
</li>
</ul>
<p>​</p>
<p>Please do not submit sensitive, personal, or confidential information, as it may be publicly accessible. Clarification: Personal Data associated to Account creation is not public.</p>

<p>Collecting and Using Your Personal Data</p>

<p>Types of Data Collected</p>

<p>Personal Data</p>
<p>​</p>
<p>While using Our Service, We collect and use only the following personal information:</p>
<p>​</p>
<ul>
<li>
<p><strong>Email Address:</strong> Required to create and authenticate your account using Google. This is used for login and communication purposes only.</p>
</li>
</ul>
<p>​</p>
<p>We do not collect or store project-related data submitted via the NoCode Flex app. All workflow automation data is publicly accessible within the demo environment and may be modified by other users.</p>
<p>​</p>
<p>Usage Data</p>
<p>​</p>
<p>We may collect Usage Data automatically when you access the Service. Usage Data may include information such as:</p>
<p>​</p>
<ul>
<li>
<p>IP address</p>
</li>
<li>
<p>Browser type</p>
</li>
<li>
<p>Browser version</p>
</li>
<li>
<p>Pages visited in the Service</p>
</li>
<li>
<p>Time and date of your visit</p>
</li>
<li>
<p>Time spent on those pages</p>
</li>
<li>
<p>Diagnostic data</p>
</li>
</ul>
<p>​</p>
<p>This data helps us improve the functionality and security of the Service.</p>
<p>​</p>
<p>Information Collected via Google Authentication</p>
<p>​</p>
<p>When You log in to NoCode Flex using Google, we may receive the following data:</p>
<p>​</p>
<ul>
<li>
<p>Your Google account’s email address (used solely for authentication purposes).</p>
</li>
<li>
<p>Basic profile information (such as name, if accessible, although not stored).</p>
</li>
</ul>
<p>​</p>
<p>You can manage permissions related to Google login through your Google account settings.</p>
<p>​</p>
<p>Use of Your Personal Data</p>
<p>​</p>
<p>The Company may use your Personal Data (i.e., email address) for the following purposes:</p>
<p>​</p>
<ul>
<li>
<p><strong>To provide and maintain our Service:</strong> We use your email to authenticate your account and enable login functionality.</p>
</li>
<li>
<p><strong>To contact You:</strong> We may send you email notifications or updates about our Service, such as security updates, technical notices, or customer support responses.</p>
</li>
<li>
<p><strong>For internal purposes:</strong> We use Usage Data to monitor and analyze usage of the Service, improve user experience, and address security issues.</p>
</li>
</ul>
<p>​</p>
<p>Data Ownership and Responsibility</p>
<p>​</p>
<p>Since NoCode Flex is a public demo application, all information submitted to the system is considered publicly accessible and may be modified by other users. NoCode Flex is not responsible for maintaining the confidentiality of any non-account-related data entered into the system.</p>
<p>​</p>
<p>User Responsibilities</p>
<p>​</p>
<p>If you use NoCode Flex, you acknowledge and agree that:</p>
<ul>
<li>
<p>You should not submit sensitive, personal, or confidential information.</p>
</li>
<li>
<p>Your contributions to the system can be modified or deleted by other users.</p>
</li>
<li>
<p>The Company is not liable for any data loss, modification, or misuse by other users.</p>
</li>
</ul>
<p>​</p>
<p>User Rights</p>
<p>​</p>
<p>As a user of NoCode Flex, You have the right to:</p>
<p>​</p>
<ul>
<li>
<p>Access or correct the data associated with your account (i.e., your email address).</p>
</li>
<li>
<p>Request the deletion of your personal data.</p>
</li>
</ul>
<p>​</p>
<p>To exercise these rights, You may do so in the application itself or by contacting us at <a href="mailto:support@lztek.io">support@lztek.io</a>, and we will process your request promptly.</p>
<p>​</p>
<p>Retention of Your Personal Data</p>
<p>​</p>
<p>The Company will retain your Personal Data (email address) only for as long as necessary to fulfill the purposes described in this Privacy Policy. Publicly submitted content may remain visible indefinitely, as the application allows open interaction and modification.</p>
<p>​</p>
<p>Security of Your Personal Data</p>
<p>​</p>
<p>We are committed to securing your Personal Data but note that no method of data transmission or storage is 100% secure. While we use commercially reasonable methods to protect your data, we cannot guarantee its absolute security.</p>
<p>​</p>
<p>Transfer of Your Personal Data</p>
<p>​</p>
<p>Your data may be transferred to, and stored on, servers located outside your jurisdiction, where data protection laws may differ. By using our Service, you consent to such transfers.</p>
<p>​</p>
<p>Disclosure of Your Personal Data</p>
<p>​</p>
<p>Your Personal Data may be disclosed under the following circumstances:</p>
<ul>
<li>
<p>Business Transactions: In the event of a merger or acquisition, your data may be transferred.</p>
</li>
<li>
<p>Law Enforcement: If required by law, we may disclose your data to public authorities.</p>
</li>
</ul>
<p>​</p>
<p>Changes to this Privacy Policy</p>
<p>​</p>
<p>We may update this Privacy Policy from time to time. You will be notified via email or a notice on the app, and the “Last updated” date will be revised accordingly.</p>
<p>​</p>
<p>Contact Us</p>
<p>​</p>
<p>If you have any questions about this Privacy Policy, contact us at:</p>
<p>​</p>
<p>Email: <a href="mailto:support@lztek.io">support@lztek.io</a></p></div><!--/$--></div></section><!--/$--></main>`;
  
  return (
    <div className="min-h-screen py-16 px-4">
      <div className="container mx-auto max-w-4xl">
        <div className="prose prose-lg max-w-none space-y-6">
          {parse(contentHtml)}
        </div>
      </div>
    </div>
  );
}

