import type { Metadata } from "next";
import parse from "html-react-parser";

export const metadata: Metadata = {
  title: "Privacy Policy | LZTEK",
  description: "Privacy Policy - LZTEK",
};

export default function ScannerPrivacyPolicy() {
  const contentHtml = `<main class="PAGE_SECTIONSf4ow4 c1rIl3" data-main-content-parent="true" id="PAGE_SECTIONSf4ow4"><!--$--><section><div><div></div><div></div></div><div><!--$--><div><p>Privacy Policy Last updated: July 19, 2024</p>
<p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.</p>
<p>Interpretation and Definitions</p>
<p>Interpretation</p>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<p>Definitions</p>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p>Account means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p>Affiliate means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p>Application means the software program provided by the Company downloaded by You on any electronic device, named LZT Scanner.</p>
</li>
<li>
<p>Company (referred to as either "the Company", "We", "Us", or "Our" in this Agreement) refers to LZTEK, LLC, 167 S 200 E, Kaysville, UT 84037.</p>
</li>
<li>
<p>Country refers to: Utah, United States</p>
</li>
<li>
<p>Device means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</p>
</li>
<li>
<p>Personal Data is any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p>Service refers to the Application.</p>
</li>
<li>
<p>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<p>Collecting and Using Your Personal Data</p>
<p>Types of Data Collected</p>
<p>Personal Data</p>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li>
<p>Entry and exit times, including your time zone</p>
</li>
<li>
<p>Work memos</p>
</li>
</ul>
<p>We only collect the time of entry and exit along with a memo of what was done for work, and no other personal data unless explicitly provided by the user.</p>
<p>Usage Data</p>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers, and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
<p>Information Collected while Using the Application</p>
<p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
<ul>
<li>
<p>Information (specifically QR codes on ID badges provided by Our Service) from your Device's camera.</p>
</li>
</ul>
<p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
<p>You can enable or disable access to this information at any time, through Your Device settings.</p>
<p>Use of Your Personal Data</p>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p>To provide and maintain our Service, including to monitor the usage of our Service.</p>
</li>
<li>
<p>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
</li>
<li>
<p>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or of any other contract with Us through the Service.</p>
</li>
<li>
<p>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates, when necessary or reasonable for their implementation.</p>
</li>
<li>
<p>To provide You with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
</li>
<li>
<p>To manage Your requests: To attend and manage Your requests to Us.</p>
</li>
<li>
<p>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
</li>
<li>
<p>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.</p>
</li>
</ul>
<p>Data Ownership and Responsibility</p>
<p>The data collected and stored through our software belongs to the companies using the service. These companies are responsible for complying with relevant data protection laws, including informing their employees about data collection practices and their rights.</p>
<p>Employee Rights</p>
<p>Employees have the right to access, correct, or delete their personal data. To exercise these rights, employees should contact their employer, who in turn can facilitate these requests through our service. If you have any concerns, you may also contact us at <a href="mailto:support@lztek.io">support@lztek.io</a>.</p>
<p>Retention of Your Personal Data</p>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Specifically, entry and exit times along with work memos will be retained for [specify duration, e.g., 1 year] unless a longer retention period is required by law. Companies using our service are responsible for retaining this data in compliance with their legal obligations.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
<p>Transfer of Your Personal Data</p>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<p>Disclosure of Your Personal Data</p>
<p>Business Transactions</p>
<p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<p>Law enforcement</p>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>
<p>Other legal requirements</p>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>
<p>Comply with a legal obligation</p>
</li>
<li>
<p>Protect and defend the rights or property of the Company</p>
</li>
<li>
<p>Prevent or investigate possible wrongdoing in connection with the Service</p>
</li>
<li>
<p>Protect the personal safety of Users of the Service or the public</p>
</li>
<li>
<p>Protect against legal liability</p>
</li>
</ul>
<p>Security of Your Personal Data</p>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<p>Children's Privacy</p>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<p>Links to Other Websites</p>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.</p>
<p>Changes to this Privacy Policy</p>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<p>Contact Us</p>

<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<p>By email: <a href="mailto:support@lztek.io">support@lztek.io</a></p></div><!--/$--></div></section><!--/$--></main>`;
  
  return (
    <div className="min-h-screen py-16 px-4">
      <div className="container mx-auto max-w-4xl">
        <div className="prose prose-lg max-w-none space-y-6">
          {parse(contentHtml)}
        </div>
      </div>
    </div>
  );
}

